spring:
  application:
    name: simple-service

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure.include: "*"
  endpoint:
    health:
      show-details: always

keycloak:
  auth-server-url: http://${KEYCLOAK_HOST:localhost}:${KEYCLOAK_PORT:8080}/auth
  realm: company-services
  resource: simple-service
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
