version: '3.5'
services:
      
  mysql-keycloak:
    image: mysql:5.7.22
    hostname: mysql-keycloak
    container_name: mysql-keycloak
    ports:
      - 3306:3306
    env_file:
     - keycloak-common.env
#    healthcheck:
#      test: ???
#      start_period: 10s

  keycloak:
    image: jboss/keycloak:4.0.0.Beta1
#    image: jboss/keycloak:3.4.3.Final # this version doesn't get up
    hostname: keycloak
    container_name: keycloak
    environment:
      - MYSQL_ADDR=mysql-keycloak
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    ports:
      - 8181:8080
    links:
      - mysql-keycloak
    env_file:
      - keycloak-common.env
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 10s
     
  ldap-service:
    image: osixia/openldap:1.2.1
    container_name: ldap-service
    hostname: ldap-service
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - 389:389
#    healthcheck:
#      test: ???
#      start_period: 10s

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.7.1
    container_name: phpldapadmin-service
    hostname: phpldapadmin-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - 6443:443
    depends_on:
      - ldap-service
    links:
      - ldap-service:ldap-host
#    healthcheck:
#      test: ???
#      start_period: 10s