version: '3.5'
services:
      
  mysql-keycloak:
    image: mysql:5.7.22
    container_name: mysql-keycloak
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"
      start_period: 10s

  keycloak:
    image: jboss/keycloak:4.0.0.Final
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - MYSQL_ADDR=mysql-keycloak
      - JDBC_PARAMS=useSSL=false
    ports:
      - 8181:8080
    links:
      - mysql-keycloak
    healthcheck:
      test: "curl -f http://localhost:8080/auth || exit 1"
      start_period: 10s
     
  ldap-service:
    image: osixia/openldap:1.2.1
    container_name: ldap-service
    environment:
      - LDAP_ORGANISATION="MyCompany Inc."
      - LDAP_DOMAIN=mycompany.com
    ports:
      - 389:389
#    healthcheck:
#      test: ???
#      start_period: 10s

  phpldapadmin-service:
    image: osixia/phpldapadmin:0.7.1
    container_name: phpldapadmin-service
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap-host
    ports:
      - 6443:443
    depends_on:
      - ldap-service
    links:
      - ldap-service:ldap-host
#    healthcheck:
#      test: ???
#      start_period: 10s