spring:
  application:
    name: springboot-keycloak-openldap
management:
  security.enabled: false
endpoints:
  beans.sensitive: false
keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: company-services
  resource: springboot-keycloak-openldap
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true