keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: company-services
  resource: springboot-keycloak-openldap
  credentials:
    secret: 04847779-73e7-49d1-ac19-973781b94276
  ssl-required: external
  principal-attribute: preferred_username