spring:
  application:
    name: springboot-keycloak-openldap

keycloak:
  auth-server-url: http://localhost:8181/auth
  realm: company-services
  resource: springboot-keycloak-openldap
  credentials:
    secret: a71dc035-92b3-4170-a64a-5480e05eb950
  ssl-required: external
  principal-attribute: preferred_username